"""add_users_table

Revision ID: c6a585053773
Revises: 
Create Date: 2026-07-24 15:50:09.057079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6a585053773'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_master_crime_sub_head_crime_head_id'), table_name='master_crime_sub_head')
    op.drop_index(op.f('ix_master_crime_sub_head_crime_sub_head_code'), table_name='master_crime_sub_head')
    op.drop_index(op.f('ix_master_crime_sub_head_crime_sub_head_name'), table_name='master_crime_sub_head')
    op.drop_index(op.f('ix_master_crime_sub_head_id'), table_name='master_crime_sub_head')
    op.drop_table('master_crime_sub_head')
    op.drop_index(op.f('ix_master_occupation_id'), table_name='master_occupation')
    op.drop_index(op.f('ix_master_occupation_occupation_code'), table_name='master_occupation')
    op.drop_index(op.f('ix_master_occupation_occupation_name'), table_name='master_occupation')
    op.drop_table('master_occupation')
    op.drop_index(op.f('ix_master_caste_caste_code'), table_name='master_caste')
    op.drop_index(op.f('ix_master_caste_caste_name'), table_name='master_caste')
    op.drop_index(op.f('ix_master_caste_id'), table_name='master_caste')
    op.drop_table('master_caste')
    op.drop_index(op.f('ix_master_gravity_offence_gravity_offence_code'), table_name='master_gravity_offence')
    op.drop_index(op.f('ix_master_gravity_offence_gravity_offence_name'), table_name='master_gravity_offence')
    op.drop_index(op.f('ix_master_gravity_offence_id'), table_name='master_gravity_offence')
    op.drop_table('master_gravity_offence')
    op.drop_index(op.f('ix_master_case_category_case_category_code'), table_name='master_case_category')
    op.drop_index(op.f('ix_master_case_category_case_category_name'), table_name='master_case_category')
    op.drop_index(op.f('ix_master_case_category_id'), table_name='master_case_category')
    op.drop_table('master_case_category')
    op.drop_index(op.f('ix_master_crime_head_crime_head_code'), table_name='master_crime_head')
    op.drop_index(op.f('ix_master_crime_head_crime_head_name'), table_name='master_crime_head')
    op.drop_index(op.f('ix_master_crime_head_id'), table_name='master_crime_head')
    op.drop_table('master_crime_head')
    op.drop_index(op.f('ix_master_religion_id'), table_name='master_religion')
    op.drop_index(op.f('ix_master_religion_religion_code'), table_name='master_religion')
    op.drop_index(op.f('ix_master_religion_religion_name'), table_name='master_religion')
    op.drop_table('master_religion')
    op.drop_index(op.f('ix_master_case_status_CaseStatusID'), table_name='master_case_status')
    op.drop_table('master_case_status')
    op.add_column('accused', sa.Column('AccusedID', sa.Integer(), nullable=False))
    op.add_column('accused', sa.Column('Name', sa.String(length=150), nullable=True))
    op.add_column('accused', sa.Column('Age', sa.Integer(), nullable=True))
    op.alter_column('accused', 'CaseMasterID',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_accused_AccusedMasterID'), table_name='accused')
    op.create_index(op.f('ix_accused_AccusedID'), 'accused', ['AccusedID'], unique=False)
    op.drop_column('accused', 'PersonID')
    op.drop_column('accused', 'AgeYear')
    op.drop_column('accused', 'AccusedName')
    op.drop_column('accused', 'GenderID')
    op.drop_column('accused', 'AccusedMasterID')
    op.add_column('arrest', sa.Column('ArrestID', sa.Integer(), nullable=False))
    op.add_column('arrest', sa.Column('ArrestDate', sa.Date(), nullable=True))
    op.drop_index(op.f('ix_arrest_ArrestSurrenderID'), table_name='arrest')
    op.create_index(op.f('ix_arrest_ArrestID'), 'arrest', ['ArrestID'], unique=False)
    op.drop_constraint(op.f('arrest_IOID_fkey'), 'arrest', type_='foreignkey')
    op.drop_constraint(op.f('arrest_CourtID_fkey'), 'arrest', type_='foreignkey')
    op.drop_constraint(op.f('arrest_AccusedMasterID_fkey'), 'arrest', type_='foreignkey')
    op.drop_constraint(op.f('arrest_ArrestSurrenderStateId_fkey'), 'arrest', type_='foreignkey')
    op.drop_constraint(op.f('arrest_PoliceStationID_fkey'), 'arrest', type_='foreignkey')
    op.drop_constraint(op.f('arrest_ArrestSurrenderDistrictId_fkey'), 'arrest', type_='foreignkey')
    op.drop_column('arrest', 'ArrestSurrenderStateId')
    op.drop_column('arrest', 'IsAccused')
    op.drop_column('arrest', 'ArrestSurrenderDate')
    op.drop_column('arrest', 'ArrestSurrenderTypeID')
    op.drop_column('arrest', 'IOID')
    op.drop_column('arrest', 'AccusedMasterID')
    op.drop_column('arrest', 'IsComplainantAccused')
    op.drop_column('arrest', 'ArrestSurrenderDistrictId')
    op.drop_column('arrest', 'CourtID')
    op.drop_column('arrest', 'PoliceStationID')
    op.drop_column('arrest', 'ArrestSurrenderID')
    op.add_column('chargesheet', sa.Column('ChargesheetID', sa.Integer(), nullable=False))
    op.add_column('chargesheet', sa.Column('FilingDate', sa.Date(), nullable=True))
    op.drop_index(op.f('ix_chargesheet_CSID'), table_name='chargesheet')
    op.create_index(op.f('ix_chargesheet_ChargesheetID'), 'chargesheet', ['ChargesheetID'], unique=False)
    op.drop_constraint(op.f('chargesheet_PolicePersonID_fkey'), 'chargesheet', type_='foreignkey')
    op.drop_column('chargesheet', 'cstype')
    op.drop_column('chargesheet', 'csdate')
    op.drop_column('chargesheet', 'CSID')
    op.drop_column('chargesheet', 'PolicePersonID')
    op.add_column('complainant', sa.Column('Name', sa.String(length=150), nullable=True))
    op.add_column('complainant', sa.Column('Phone', sa.String(length=20), nullable=True))
    op.add_column('complainant', sa.Column('Address', sa.String(length=255), nullable=True))
    op.alter_column('complainant', 'CaseMasterID',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('complainant_OccupationID_fkey'), 'complainant', type_='foreignkey')
    op.drop_constraint(op.f('complainant_CasteID_fkey'), 'complainant', type_='foreignkey')
    op.drop_constraint(op.f('complainant_ReligionID_fkey'), 'complainant', type_='foreignkey')
    op.drop_column('complainant', 'ReligionID')
    op.drop_column('complainant', 'AgeYear')
    op.drop_column('complainant', 'CasteID')
    op.drop_column('complainant', 'ComplainantName')
    op.drop_column('complainant', 'GenderID')
    op.drop_column('complainant', 'OccupationID')
    op.drop_constraint(op.f('court_StateID_fkey'), 'court', type_='foreignkey')
    op.drop_constraint(op.f('court_DistrictID_fkey'), 'court', type_='foreignkey')
    op.drop_column('court', 'StateID')
    op.drop_column('court', 'DistrictID')
    op.drop_column('court', 'Active')
    op.alter_column('crime_head', 'CrimeGroupName',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_index(op.f('ix_crime_head_CrimeHeadID'), table_name='crime_head')
    op.drop_column('designation', 'SortOrder')
    op.drop_column('designation', 'Active')
    op.alter_column('district', 'DistrictName',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_index(op.f('ix_district_DistrictID'), table_name='district')
    op.drop_column('district', 'Active')
    op.add_column('employee', sa.Column('EmployeeName', sa.String(length=150), nullable=True))
    op.alter_column('employee', 'RankID',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('employee', 'DesignationID',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('employee_KGID_key'), 'employee', type_='unique')
    op.drop_index(op.f('ix_employee_EmployeeID'), table_name='employee')
    op.drop_constraint(op.f('employee_DistrictID_fkey'), 'employee', type_='foreignkey')
    op.drop_constraint(op.f('employee_UnitID_fkey'), 'employee', type_='foreignkey')
    op.drop_column('employee', 'FirstName')
    op.drop_column('employee', 'UnitID')
    op.drop_column('employee', 'DistrictID')
    op.drop_column('employee', 'KGID')
    op.drop_column('employee', 'EmployeeDOB')
    op.drop_column('employee', 'AppointmentDate')
    op.drop_column('employee', 'GenderID')
    op.drop_column('employee', 'PhysicallyChallenged')
    op.drop_column('employee', 'BloodGroupID')
    op.drop_column('rank', 'Active')
    op.drop_column('rank', 'Hierarchy')
    op.drop_column('state', 'Active')
    op.drop_column('state', 'NationalityID')
    op.add_column('unit', sa.Column('UnitTypeID', sa.Integer(), nullable=True))
    op.alter_column('unit', 'UnitName',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.drop_constraint(op.f('unit_StateID_fkey'), 'unit', type_='foreignkey')
    op.drop_constraint(op.f('unit_TypeID_fkey'), 'unit', type_='foreignkey')
    op.create_foreign_key(None, 'unit', 'unit_type', ['UnitTypeID'], ['UnitTypeID'])
    op.drop_column('unit', 'StateID')
    op.drop_column('unit', 'NationalityID')
    op.drop_column('unit', 'Active')
    op.drop_column('unit', 'TypeID')
    op.drop_column('unit', 'ParentUnit')
    op.add_column('unit_type', sa.Column('LookupValue', sa.String(length=100), nullable=True))
    op.drop_index(op.f('ix_unit_type_UnitTypeID'), table_name='unit_type')
    op.drop_column('unit_type', 'Active')
    op.drop_column('unit_type', 'Hierarchy')
    op.drop_column('unit_type', 'CityDistState')
    op.drop_column('unit_type', 'UnitTypeName')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.add_column('victim', sa.Column('VictimID', sa.Integer(), nullable=False))
    op.add_column('victim', sa.Column('Name', sa.String(length=150), nullable=True))
    op.add_column('victim', sa.Column('Age', sa.Integer(), nullable=True))
    op.add_column('victim', sa.Column('Gender', sa.String(length=10), nullable=True))
    op.alter_column('victim', 'CaseMasterID',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_victim_VictimMasterID'), table_name='victim')
    op.create_index(op.f('ix_victim_VictimID'), 'victim', ['VictimID'], unique=False)
    op.drop_column('victim', 'AgeYear')
    op.drop_column('victim', 'VictimMasterID')
    op.drop_column('victim', 'VictimPolice')
    op.drop_column('victim', 'VictimName')
    op.drop_column('victim', 'GenderID')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('victim', sa.Column('GenderID', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('victim', sa.Column('VictimName', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('victim', sa.Column('VictimPolice', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    op.add_column('victim', sa.Column('VictimMasterID', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('victim', sa.Column('AgeYear', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_victim_VictimID'), table_name='victim')
    op.create_index(op.f('ix_victim_VictimMasterID'), 'victim', ['VictimMasterID'], unique=False)
    op.alter_column('victim', 'CaseMasterID',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('victim', 'Gender')
    op.drop_column('victim', 'Age')
    op.drop_column('victim', 'Name')
    op.drop_column('victim', 'VictimID')
    op.alter_column('users', 'full_name',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.add_column('unit_type', sa.Column('UnitTypeName', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('unit_type', sa.Column('CityDistState', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('unit_type', sa.Column('Hierarchy', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('unit_type', sa.Column('Active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_unit_type_UnitTypeID'), 'unit_type', ['UnitTypeID'], unique=False)
    op.drop_column('unit_type', 'LookupValue')
    op.add_column('unit', sa.Column('ParentUnit', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('unit', sa.Column('TypeID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('unit', sa.Column('Active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('unit', sa.Column('NationalityID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('unit', sa.Column('StateID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'unit', type_='foreignkey')
    op.create_foreign_key(op.f('unit_TypeID_fkey'), 'unit', 'unit_type', ['TypeID'], ['UnitTypeID'])
    op.create_foreign_key(op.f('unit_StateID_fkey'), 'unit', 'state', ['StateID'], ['StateID'])
    op.alter_column('unit', 'UnitName',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
    op.drop_column('unit', 'UnitTypeID')
    op.add_column('state', sa.Column('NationalityID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('state', sa.Column('Active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('rank', sa.Column('Hierarchy', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('rank', sa.Column('Active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('employee', sa.Column('BloodGroupID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('employee', sa.Column('PhysicallyChallenged', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('employee', sa.Column('GenderID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('employee', sa.Column('AppointmentDate', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('employee', sa.Column('EmployeeDOB', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('employee', sa.Column('KGID', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('employee', sa.Column('DistrictID', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('employee', sa.Column('UnitID', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('employee', sa.Column('FirstName', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('employee_UnitID_fkey'), 'employee', 'unit', ['UnitID'], ['UnitID'])
    op.create_foreign_key(op.f('employee_DistrictID_fkey'), 'employee', 'district', ['DistrictID'], ['DistrictID'])
    op.create_index(op.f('ix_employee_EmployeeID'), 'employee', ['EmployeeID'], unique=False)
    op.create_unique_constraint(op.f('employee_KGID_key'), 'employee', ['KGID'], postgresql_nulls_not_distinct=False)
    op.alter_column('employee', 'DesignationID',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('employee', 'RankID',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('employee', 'EmployeeName')
    op.add_column('district', sa.Column('Active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_district_DistrictID'), 'district', ['DistrictID'], unique=False)
    op.alter_column('district', 'DistrictName',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.add_column('designation', sa.Column('Active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('designation', sa.Column('SortOrder', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_crime_head_CrimeHeadID'), 'crime_head', ['CrimeHeadID'], unique=False)
    op.alter_column('crime_head', 'CrimeGroupName',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.add_column('court', sa.Column('Active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('court', sa.Column('DistrictID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('court', sa.Column('StateID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('court_DistrictID_fkey'), 'court', 'district', ['DistrictID'], ['DistrictID'])
    op.create_foreign_key(op.f('court_StateID_fkey'), 'court', 'state', ['StateID'], ['StateID'])
    op.add_column('complainant', sa.Column('OccupationID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('complainant', sa.Column('GenderID', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('complainant', sa.Column('ComplainantName', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('complainant', sa.Column('CasteID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('complainant', sa.Column('AgeYear', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('complainant', sa.Column('ReligionID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('complainant_ReligionID_fkey'), 'complainant', 'religion', ['ReligionID'], ['ReligionID'])
    op.create_foreign_key(op.f('complainant_CasteID_fkey'), 'complainant', 'caste', ['CasteID'], ['caste_master_id'])
    op.create_foreign_key(op.f('complainant_OccupationID_fkey'), 'complainant', 'occupation', ['OccupationID'], ['OccupationID'])
    op.alter_column('complainant', 'CaseMasterID',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('complainant', 'Address')
    op.drop_column('complainant', 'Phone')
    op.drop_column('complainant', 'Name')
    op.add_column('chargesheet', sa.Column('PolicePersonID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('chargesheet', sa.Column('CSID', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('chargesheet', sa.Column('csdate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('chargesheet', sa.Column('cstype', sa.VARCHAR(length=1), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('chargesheet_PolicePersonID_fkey'), 'chargesheet', 'employee', ['PolicePersonID'], ['EmployeeID'])
    op.drop_index(op.f('ix_chargesheet_ChargesheetID'), table_name='chargesheet')
    op.create_index(op.f('ix_chargesheet_CSID'), 'chargesheet', ['CSID'], unique=False)
    op.drop_column('chargesheet', 'FilingDate')
    op.drop_column('chargesheet', 'ChargesheetID')
    op.add_column('arrest', sa.Column('ArrestSurrenderID', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('arrest', sa.Column('PoliceStationID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('arrest', sa.Column('CourtID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('arrest', sa.Column('ArrestSurrenderDistrictId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('arrest', sa.Column('IsComplainantAccused', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('arrest', sa.Column('AccusedMasterID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('arrest', sa.Column('IOID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('arrest', sa.Column('ArrestSurrenderTypeID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('arrest', sa.Column('ArrestSurrenderDate', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('arrest', sa.Column('IsAccused', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('arrest', sa.Column('ArrestSurrenderStateId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('arrest_ArrestSurrenderDistrictId_fkey'), 'arrest', 'district', ['ArrestSurrenderDistrictId'], ['DistrictID'])
    op.create_foreign_key(op.f('arrest_PoliceStationID_fkey'), 'arrest', 'unit', ['PoliceStationID'], ['UnitID'])
    op.create_foreign_key(op.f('arrest_ArrestSurrenderStateId_fkey'), 'arrest', 'state', ['ArrestSurrenderStateId'], ['StateID'])
    op.create_foreign_key(op.f('arrest_AccusedMasterID_fkey'), 'arrest', 'accused', ['AccusedMasterID'], ['AccusedMasterID'])
    op.create_foreign_key(op.f('arrest_CourtID_fkey'), 'arrest', 'court', ['CourtID'], ['CourtID'])
    op.create_foreign_key(op.f('arrest_IOID_fkey'), 'arrest', 'employee', ['IOID'], ['EmployeeID'])
    op.drop_index(op.f('ix_arrest_ArrestID'), table_name='arrest')
    op.create_index(op.f('ix_arrest_ArrestSurrenderID'), 'arrest', ['ArrestSurrenderID'], unique=False)
    op.drop_column('arrest', 'ArrestDate')
    op.drop_column('arrest', 'ArrestID')
    op.add_column('accused', sa.Column('AccusedMasterID', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('accused', sa.Column('GenderID', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('accused', sa.Column('AccusedName', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('accused', sa.Column('AgeYear', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('accused', sa.Column('PersonID', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_accused_AccusedID'), table_name='accused')
    op.create_index(op.f('ix_accused_AccusedMasterID'), 'accused', ['AccusedMasterID'], unique=False)
    op.alter_column('accused', 'CaseMasterID',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('accused', 'Age')
    op.drop_column('accused', 'Name')
    op.drop_column('accused', 'AccusedID')
    op.create_table('master_case_status',
    sa.Column('CaseStatusID', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('CaseStatusName', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('CaseStatusID', name=op.f('master_case_status_pkey'))
    )
    op.create_index(op.f('ix_master_case_status_CaseStatusID'), 'master_case_status', ['CaseStatusID'], unique=False)
    op.create_table('master_religion',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('religion_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('religion_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('master_religion_pkey'))
    )
    op.create_index(op.f('ix_master_religion_religion_name'), 'master_religion', ['religion_name'], unique=False)
    op.create_index(op.f('ix_master_religion_religion_code'), 'master_religion', ['religion_code'], unique=True)
    op.create_index(op.f('ix_master_religion_id'), 'master_religion', ['id'], unique=False)
    op.create_table('master_crime_head',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('crime_head_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('crime_head_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('master_crime_head_pkey'))
    )
    op.create_index(op.f('ix_master_crime_head_id'), 'master_crime_head', ['id'], unique=False)
    op.create_index(op.f('ix_master_crime_head_crime_head_name'), 'master_crime_head', ['crime_head_name'], unique=False)
    op.create_index(op.f('ix_master_crime_head_crime_head_code'), 'master_crime_head', ['crime_head_code'], unique=True)
    op.create_table('master_case_category',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('case_category_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('case_category_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('master_case_category_pkey'))
    )
    op.create_index(op.f('ix_master_case_category_id'), 'master_case_category', ['id'], unique=False)
    op.create_index(op.f('ix_master_case_category_case_category_name'), 'master_case_category', ['case_category_name'], unique=False)
    op.create_index(op.f('ix_master_case_category_case_category_code'), 'master_case_category', ['case_category_code'], unique=True)
    op.create_table('master_gravity_offence',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('gravity_offence_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('gravity_offence_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('master_gravity_offence_pkey'))
    )
    op.create_index(op.f('ix_master_gravity_offence_id'), 'master_gravity_offence', ['id'], unique=False)
    op.create_index(op.f('ix_master_gravity_offence_gravity_offence_name'), 'master_gravity_offence', ['gravity_offence_name'], unique=False)
    op.create_index(op.f('ix_master_gravity_offence_gravity_offence_code'), 'master_gravity_offence', ['gravity_offence_code'], unique=True)
    op.create_table('master_caste',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('caste_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('caste_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('master_caste_pkey'))
    )
    op.create_index(op.f('ix_master_caste_id'), 'master_caste', ['id'], unique=False)
    op.create_index(op.f('ix_master_caste_caste_name'), 'master_caste', ['caste_name'], unique=False)
    op.create_index(op.f('ix_master_caste_caste_code'), 'master_caste', ['caste_code'], unique=True)
    op.create_table('master_occupation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('occupation_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('occupation_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('master_occupation_pkey'))
    )
    op.create_index(op.f('ix_master_occupation_occupation_name'), 'master_occupation', ['occupation_name'], unique=False)
    op.create_index(op.f('ix_master_occupation_occupation_code'), 'master_occupation', ['occupation_code'], unique=True)
    op.create_index(op.f('ix_master_occupation_id'), 'master_occupation', ['id'], unique=False)
    op.create_table('master_crime_sub_head',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('crime_sub_head_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('crime_sub_head_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('crime_head_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['crime_head_id'], ['master_crime_head.id'], name=op.f('master_crime_sub_head_crime_head_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('master_crime_sub_head_pkey'))
    )
    op.create_index(op.f('ix_master_crime_sub_head_id'), 'master_crime_sub_head', ['id'], unique=False)
    op.create_index(op.f('ix_master_crime_sub_head_crime_sub_head_name'), 'master_crime_sub_head', ['crime_sub_head_name'], unique=False)
    op.create_index(op.f('ix_master_crime_sub_head_crime_sub_head_code'), 'master_crime_sub_head', ['crime_sub_head_code'], unique=True)
    op.create_index(op.f('ix_master_crime_sub_head_crime_head_id'), 'master_crime_sub_head', ['crime_head_id'], unique=False)
    # ### end Alembic commands ###
